# Generated by Django 3.2 on 2021-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationWebApp', '0002_auto_20210827_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfordonation',
            name='Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requestfordonation',
            name='CNIC',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='requestfordonation',
            name='Contact_Number',
            field=models.CharField(max_length=16),
        ),
    ]
